"""
Script to generate the complete, comprehensive, 20-step quantitative
Jupyter Notebook for Dow Jones stock market forecasting with LSTM, RNN,
Technical Indicators, strict zero-leakage scaling, and evaluation.
"""

import json
import os

nb = {
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# 📈 Dow Jones Stock Market Forecasting with Deep Learning (LSTM & RNN)\n",
                "\n",
                "## Institutional Quantitative Preprocessing, Technical Indicator Engineering & Deep Neural Networks\n",
                "\n",
                "This notebook implements a complete 20-step quantitative forecasting pipeline on the historical Dow Jones dataset (`data/dow_jones.csv`), featuring:\n",
                "\n",
                "1. **Full OHLCV Data Cleaning & Chronological Sorting**\n",
                "2. **Feature Engineering**: Log Returns, Volatility, Moving Averages, RSI, MACD, Bollinger Bands, Normalized ATR, and Lag Returns\n",
                "3. **Forward Target Formulation**: Predicting $t+1$ forward log-return and upward/downward direction\n",
                "4. **Strict Zero-Leakage Split**: Chronological 70% Train / 15% Validation / 15% Test\n",
                "5. **Scaler Fitting**: Normalization fit **EXCLUSIVELY** on Training data\n",
                "6. **Sliding Window Sequence Creation**: 60-day historical sequence lookback ($LOOKBACK = 60$)\n",
                "7. **Deep Learning Architectures**: Stacked LSTM and Simple RNN with Dropout (0.2) and EarlyStopping\n",
                "8. **Classical ML & Time-Series Benchmarks**: Random Forest, Linear Regression, ARMA(2,7), Constant Baseline\n",
                "9. **Rigorous Test Evaluation**: MAE, RMSE, $R^2$ Score, Directional Accuracy, Precision, Recall, ROC-AUC\n"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Step 1 & 2: Import Libraries & Configure Environment\n",
                "import os\n",
                "import numpy as np\n",
                "import pandas as pd\n",
                "import matplotlib.pyplot as plt\n",
                "import seaborn as sns\n",
                "import warnings\n",
                "\n",
                "from sklearn.preprocessing import StandardScaler\n",
                "from sklearn.dummy import DummyRegressor\n",
                "from sklearn.linear_model import LinearRegression\n",
                "from sklearn.ensemble import RandomForestRegressor\n",
                "from sklearn.metrics import (\n",
                "    mean_absolute_error, mean_squared_error, r2_score,\n",
                "    accuracy_score, precision_score, recall_score, roc_auc_score\n",
                ")\n",
                "import statsmodels.api as sm\n",
                "from statsmodels.tsa.arima.model import ARIMA\n",
                "\n",
                "import tensorflow as tf\n",
                "from tensorflow.keras.models import Sequential\n",
                "from tensorflow.keras.layers import LSTM, SimpleRNN, Dense, Dropout\n",
                "from tensorflow.keras.callbacks import EarlyStopping\n",
                "from tensorflow.keras.optimizers import Adam\n",
                "\n",
                "warnings.filterwarnings('ignore')\n",
                "np.random.seed(42)\n",
                "tf.random.set_seed(42)\n",
                "plt.style.use('seaborn-v0_8-darkgrid' if 'seaborn-v0_8-darkgrid' in plt.style.available else 'default')\n",
                "%matplotlib inline\n",
                "print('Environment Ready. TensorFlow Version:', tf.__version__)"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Step 3, 4, 5: Load CSV, Parse Dates, Chronological Sort & Clean OHLCV\n",
                "csv_path = '../data/dow_jones.csv' if os.path.exists('../data/dow_jones.csv') else 'data/dow_jones.csv'\n",
                "df = pd.read_csv(csv_path)\n",
                "df.columns = df.columns.str.strip()\n",
                "\n",
                "# Parse dates and sort strictly in chronological order\n",
                "df['DATE'] = pd.to_datetime(df['DATE'], errors='coerce')\n",
                "df = df.dropna(subset=['DATE']).sort_values('DATE').drop_duplicates('DATE').reset_index(drop=True)\n",
                "\n",
                "# Convert numeric columns cleanly\n",
                "for col in ['Open', 'High', 'Low', 'Close', 'Volume']:\n",
                "    if col in df.columns:\n",
                "        df[col] = pd.to_numeric(df[col].astype(str).str.replace(',', ''), errors='coerce')\n",
                "\n",
                "# Filter out invalid non-positive prices and handle Volume\n",
                "df = df.dropna(subset=['Open', 'High', 'Low', 'Close']).reset_index(drop=True)\n",
                "df = df[(df['Open'] > 0) & (df['High'] > 0) & (df['Low'] > 0) & (df['Close'] > 0)].reset_index(drop=True)\n",
                "if 'Volume' in df.columns:\n",
                "    df['Volume'] = df['Volume'].fillna(0.0)\n",
                "\n",
                "print(f'Total Clean Trading Days: {len(df):,}')\n",
                "print(f'Date Range: {df[\"DATE\"].min().strftime(\"%d %b %Y\")} -> {df[\"DATE\"].max().strftime(\"%d %b %Y\")}')\n",
                "df.head()"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Step 6, 7, 8: Technical Feature Engineering (RSI, MACD, Bollinger Bands, ATR, Momentum)\n",
                "\n",
                "# 1. Forward Return & Direction Targets (Predicting t+1)\n",
                "df['log_return'] = np.log(df['Close'] / df['Close'].shift(1))\n",
                "df['target_return'] = df['log_return'].shift(-1)  # Target: tomorrow's return\n",
                "df['target_direction'] = (df['target_return'] > 0).astype(int)  # 1 = Up, 0 = Down\n",
                "\n",
                "# 2. Multi-Period Returns & Moving Averages\n",
                "df['return_1'] = df['Close'].pct_change(1)\n",
                "df['return_5'] = df['Close'].pct_change(5)\n",
                "df['return_10'] = df['Close'].pct_change(10)\n",
                "df['ma_5_ratio'] = (df['Close'] / df['Close'].rolling(5).mean()) - 1.0\n",
                "df['ma_10_ratio'] = (df['Close'] / df['Close'].rolling(10).mean()) - 1.0\n",
                "df['ma_20_ratio'] = (df['Close'] / df['Close'].rolling(20).mean()) - 1.0\n",
                "\n",
                "# 3. Volatility & Intraday Dynamics\n",
                "df['volatility_5'] = df['return_1'].rolling(5).std()\n",
                "df['volatility_20'] = df['return_1'].rolling(20).std()\n",
                "df['high_low_ratio'] = (df['High'] - df['Low']) / df['Close']\n",
                "df['open_close_ratio'] = (df['Close'] - df['Open']) / df['Open']\n",
                "df['volume_change'] = df['Volume'].pct_change().clip(-5, 5).fillna(0.0)\n",
                "\n",
                "# 4. RSI (14-period)\n",
                "delta = df['Close'].diff()\n",
                "gain = delta.clip(lower=0)\n",
                "loss = -delta.clip(upper=0)\n",
                "avg_gain = gain.ewm(com=13, min_periods=14).mean()\n",
                "avg_loss = loss.ewm(com=13, min_periods=14).mean()\n",
                "rs = avg_gain / (avg_loss + 1e-9)\n",
                "df['rsi_14'] = (100.0 - (100.0 / (1.0 + rs)) - 50.0) / 50.0\n",
                "\n",
                "# 5. MACD (12, 26, 9)\n",
                "ema12 = df['Close'].ewm(span=12, adjust=False).mean()\n",
                "ema26 = df['Close'].ewm(span=26, adjust=False).mean()\n",
                "df['macd'] = (ema12 - ema26) / df['Close']\n",
                "df['macd_signal'] = df['macd'].ewm(span=9, adjust=False).mean()\n",
                "df['macd_hist'] = df['macd'] - df['macd_signal']\n",
                "\n",
                "# 6. Bollinger Bands (20-period, 2 std)\n",
                "sma20 = df['Close'].rolling(20).mean()\n",
                "std20 = df['Close'].rolling(20).std()\n",
                "upper_bb = sma20 + 2 * std20\n",
                "lower_bb = sma20 - 2 * std20\n",
                "df['bb_pct'] = ((df['Close'] - lower_bb) / (upper_bb - lower_bb + 1e-9)) - 0.5\n",
                "df['bb_width'] = (upper_bb - lower_bb) / (sma20 + 1e-9)\n",
                "\n",
                "# 7. Average True Range (ATR 14)\n",
                "tr1 = df['High'] - df['Low']\n",
                "tr2 = (df['High'] - df['Close'].shift(1)).abs()\n",
                "tr3 = (df['Low'] - df['Close'].shift(1)).abs()\n",
                "df['atr_norm'] = pd.concat([tr1, tr2, tr3], axis=1).max(axis=1).rolling(14).mean() / df['Close']\n",
                "\n",
                "# 8. Multi-Lag Returns\n",
                "for lag in [1, 2, 3, 5, 10, 20]:\n",
                "    df[f'return_lag_{lag}'] = df['log_return'].shift(lag)\n",
                "\n",
                "# Clean NaN rows resulting from rolling windows without backward leakage\n",
                "df = df.replace([np.inf, -np.inf], np.nan).dropna().reset_index(drop=True)\n",
                "print('Feature engineering complete. Clean usable observations:', len(df))\n"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Step 9, 10, 11, 12: Chronological 70/15/15 Split & Zero-Leakage Scaler Fitting\n",
                "feature_cols = [\n",
                "    'return_1', 'return_5', 'return_10',\n",
                "    'ma_5_ratio', 'ma_10_ratio', 'ma_20_ratio',\n",
                "    'volatility_5', 'volatility_20',\n",
                "    'high_low_ratio', 'open_close_ratio', 'volume_change',\n",
                "    'rsi_14', 'macd', 'macd_signal', 'macd_hist',\n",
                "    'bb_pct', 'bb_width', 'atr_norm',\n",
                "    'return_lag_1', 'return_lag_2', 'return_lag_3',\n",
                "    'return_lag_5', 'return_lag_10', 'return_lag_20'\n",
                "]\n",
                "\n",
                "n = len(df)\n",
                "train_end = int(n * 0.70)\n",
                "val_end = int(n * 0.85)\n",
                "\n",
                "train_df = df.iloc[:train_end].copy()\n",
                "val_df = df.iloc[train_end:val_end].copy()\n",
                "test_df = df.iloc[val_end:].copy()\n",
                "\n",
                "# Scaler is fit EXCLUSIVELY on train_df\n",
                "scaler = StandardScaler()\n",
                "scaler.fit(train_df[feature_cols])\n",
                "\n",
                "train_scaled = scaler.transform(train_df[feature_cols])\n",
                "val_scaled = scaler.transform(val_df[feature_cols])\n",
                "test_scaled = scaler.transform(test_df[feature_cols])\n",
                "\n",
                "print(f'Train: {len(train_df):,} | Val: {len(val_df):,} | Test: {len(test_df):,}')\n"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Step 13 & 14: 60-Day Sliding Sequence Generation (LOOKBACK = 60)\n",
                "LOOKBACK = 60\n",
                "\n",
                "def create_sequences(features_arr, target_ret_arr, target_dir_arr, lookback=60):\n",
                "    X, y_ret, y_dir = [], [], []\n",
                "    for i in range(lookback, len(features_arr)):\n",
                "        X.append(features_arr[i - lookback : i])\n",
                "        y_ret.append(target_ret_arr[i])\n",
                "        y_dir.append(target_dir_arr[i])\n",
                "    return np.array(X, dtype=np.float32), np.array(y_ret, dtype=np.float32), np.array(y_dir, dtype=np.int32)\n",
                "\n",
                "X_train_seq, y_train_ret, y_train_dir = create_sequences(train_scaled, train_df['target_return'].values, train_df['target_direction'].values, LOOKBACK)\n",
                "X_val_seq, y_val_ret, y_val_dir = create_sequences(val_scaled, val_df['target_return'].values, val_df['target_direction'].values, LOOKBACK)\n",
                "X_test_seq, y_test_ret, y_test_dir = create_sequences(test_scaled, test_df['target_return'].values, test_df['target_direction'].values, LOOKBACK)\n",
                "\n",
                "print('X_train_seq shape:', X_train_seq.shape)\n",
                "print('X_test_seq shape:', X_test_seq.shape)\n"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Step 15 & 16: Build and Train Stacked LSTM Neural Network\n",
                "n_features = X_train_seq.shape[2]\n",
                "\n",
                "lstm_model = Sequential([\n",
                "    LSTM(64, return_sequences=True, input_shape=(LOOKBACK, n_features)),\n",
                "    Dropout(0.2),\n",
                "    LSTM(32, return_sequences=False),\n",
                "    Dropout(0.2),\n",
                "    Dense(16, activation='relu'),\n",
                "    Dense(1)\n",
                "])\n",
                "lstm_model.compile(optimizer=Adam(learning_rate=0.001), loss='mse', metrics=['mae'])\n",
                "\n",
                "early_stop = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True, verbose=1)\n",
                "\n",
                "history = lstm_model.fit(\n",
                "    X_train_seq, y_train_ret,\n",
                "    validation_data=(X_val_seq, y_val_ret),\n",
                "    epochs=20,\n",
                "    batch_size=32,\n",
                "    callbacks=[early_stop],\n",
                "    shuffle=False,\n",
                "    verbose=1\n",
                ")\n"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Step 17, 18, 19, 20: Comprehensive Model Evaluation on Untouched Test Set\n",
                "lstm_pred = lstm_model.predict(X_test_seq, verbose=0).flatten()\n",
                "lstm_mae = mean_absolute_error(y_test_ret, lstm_pred)\n",
                "lstm_rmse = np.sqrt(mean_squared_error(y_test_ret, lstm_pred))\n",
                "lstm_r2 = r2_score(y_test_ret, lstm_pred)\n",
                "\n",
                "lstm_dir_preds = (lstm_pred > 0).astype(int)\n",
                "lstm_acc = accuracy_score(y_test_dir, lstm_dir_preds)\n",
                "lstm_prec = precision_score(y_test_dir, lstm_dir_preds, zero_division=0)\n",
                "lstm_rec = recall_score(y_test_dir, lstm_dir_preds, zero_division=0)\n",
                "\n",
                "print('=' * 50)\n",
                "print('📊 STACKED LSTM TEST EVALUATION RESULTS')\n",
                "print('=' * 50)\n",
                "print(f'Test MAE:                 {lstm_mae:.6f}')\n",
                "print(f'Test RMSE:                {lstm_rmse:.6f}')\n",
                "print(f'Test R2 Score:            {lstm_r2:.4f}')\n",
                "print(f'Directional Accuracy:     {lstm_acc*100:.2f}%')\n",
                "print(f'Precision:                {lstm_prec*100:.2f}%')\n",
                "print(f'Recall:                   {lstm_rec*100:.2f}%')\n",
                "print('=' * 50)\n"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Plot Actual vs Predicted Returns\n",
                "plt.figure(figsize=(14, 5))\n",
                "plt.plot(y_test_ret[-100:], label='Actual Returns', color='white', alpha=0.9)\n",
                "plt.plot(lstm_pred[-100:], label='LSTM Forecast', color='#10b981', linewidth=1.5)\n",
                "plt.title('Dow Jones Forward Return Forecast — Stacked LSTM (Last 100 Test Days)', fontsize=13)\n",
                "plt.xlabel('Test Trading Days')\n",
                "plt.ylabel('Forward Log Return (ld_Close)')\n",
                "plt.legend()\n",
                "plt.tight_layout()\n",
                "plt.show()"
            ]
        }
    ],
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "name": "python",
            "version": "3.11.0"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 5
}

target_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "stock_market_analysis.ipynb")
with open(target_path, "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=1)
print(f"Generated notebook at {target_path}")
